Make error handling more robust
From logs we are occasionally not setting an error
and this is causing

TypeError: Invalid status code: null. Status code must be an integer.

Change-Id: I5bc59249750edaee1c29b1f3aec48844b276deb7